Sub CATMain()

Dim fileloc As String
fileloc = CATIA.ActiveDocument.Path & "\"

Dim prodname As String
prodname = CATIA.ActiveDocument.Name

Dim strfilecatia As String
strfilecatia = fileloc & prodname

Dim strfileOhne As String
strfileOhne = Left(strfilecatia, (InStrRev(strfilecatia, ".") - 1))

Dim strfileasp As String
strfileasp = strfileOhne & ".scdoc"

Dim tempfolder As String
tempfolder = fileloc & "temp\"

'create temp folder

If Len(Dir(tempfolder, vbDirectory)) = 0 Then
   MkDir tempfolder
End If


Dim Answer As VbMsgBoxResult
Dim Message As String
Dim HeadlessAnswer As String
Dim ExitAfterScriptAnswer As String
Dim SplashAnswer As String

Message = "Do you want to open Ansys Speos for the import?"
Answer = MsgBox(Message, vbYesNo + vbQuestion, "Ansys Speos")

If Answer = vbYes Then
    HeadlessAnswer = "Headless=False"
    ExitAfterScriptAnswer = "ExitAfterScript=False"
    SplashAnswer = "Splash=True"
Else
    HeadlessAnswer = "Headless=True"
    ExitAfterScriptAnswer = "ExitAfterScript=True"
    SplashAnswer = "Splash=False"
End If


Dim templatepath As String
Dim lineone As String
Dim linetwo As String
Dim templateanswer As String

Message = "Do you want to import a Spaceclaim Template?"
Answer = MsgBox(Message, vbYesNo + vbQuestion, "Template")

If Answer = vbYes Then
    templatepath = CATIA.FileSelectionBox("Select Spaceclaim template", "*.scdot", CatFileSelectionModeOpen)
    lineone = "DocumentOpen.Execute(r""" & templatepath & """, importOptions, GetMaps(""cacd1ed1""))"
    linetwo = "DocumentInsert.Execute(r""" & strfilecatia & """, importOptions, GetMaps(""cacd1ed1""))"
    templateanswer = lineone & vbCr & linetwo
    
    Else
    
    templateanswer = "DocumentOpen.Execute(r""" & strfilecatia & """, importOptions, GetMaps(""cacd1ed1""))"

End If


'create phyton script to load and save project

Set fs = CreateObject("Scripting.FileSystemObject")
    Set A = fs.CreateTextFile(tempfolder & "scriptconversion.ipy", True)
    A.WriteLine ("import System")
    A.WriteLine ("import os")
    A.WriteLine ("import time")
    A.WriteLine ("importOptions = ImportOptions.Create()")
    A.WriteLine ("importOptions.ImportPoints =True")
    A.WriteLine ("importOptions.ImportCurves =True")
    A.WriteLine ("importOptions.ImportNames =True")
    A.WriteLine (templateanswer)
    A.WriteLine ("options = ExportOptions.Create()")
    A.WriteLine ("DocumentSave.Execute(r""" & strfileasp & """, options)")
    A.Close

'create .bat file to execute ASP and delete temp folder

Set fs = CreateObject("Scripting.FileSystemObject")
    Set A = fs.CreateTextFile(tempfolder & "scriptconversion.bat", True)
    A.WriteLine ("""C:\Program Files\ANSYS Inc\v202\scdm\spaceclaim.exe"" /AddInManifestFile=""C:\Program Files\ANSYS Inc\v202\Optical Products\SPEOS\Bin\SpeosSC.Manifest.xml"" /RunScript=""scriptconversion.ipy"" /" & HeadlessAnswer & " /" & SplashAnswer & " /Welcome=False /" & ExitAfterScriptAnswer & "")
    A.WriteLine ("cd ..")
    A.WriteLine ("@RD /S /Q """ & tempfolder & """")
    A.Close

Dim striptloc As String
scriptloc = "ChDir /d " & tempfolder & " &&" & " scriptconversion.bat"

'execute batfile

Call Shell("CMD.EXE /C" & scriptloc, vbMinimizedNoFocus)

End Sub